apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-policy-controller-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-policy-controller-leader-election
subjects:
- kind: ServiceAccount
  name: cert-policy-controller
  namespace: open-cluster-management-agent-addon
